import type { ConsultingKnowledgeEntry } from "../../../../shared/consulting-knowledge.schema.js"

// The curated Customer Operations content the Consulting Knowledge Base ships
// with. It is *initial* content, not a fixture: an administrator curates on top
// of it, and the seed never runs again once the base holds anything
// (see `consulting-knowledge.repository.ts`).
//
// Every entry carries its typed relationships — which taxonomy node, which
// process, which problem, which use case it belongs to — because those
// relationships, not its tags, are what retrieval traverses.

type ProcessSeed = {
  code: string
  title: string
  summary: string
  tags: string[]
  taxonomyCodes: string[]
  // The curated vocabulary that resolves an engagement's own words into this
  // process's code. It is the only place free text meets curated knowledge.
  matchTerms: string[]
}

type TaxonomySeed = {
  code: string
  title: string
  summary: string
  processCode: string
  matchTerms: string[]
}

type UseCaseSeed = {
  code: string
  title: string
  summary: string
  processCode: string
  taxonomyCodes: string[]
  patterns: string[]
  implementationPatterns: string[]
  roiModels: string[]
  riskModels: string[]
  questions: string[]
  criteria: string[]
  bestPractices: string[]
  followUps: string[]
  signals: string[]
  steps: string[]
  risks: string[]
  mitigations: string[]
  roiDrivers: string[]
}

type GenericSeed = {
  code: string
  kind: ConsultingKnowledgeEntry["kind"]
  title: string
  summary: string
  tags: string[]
  matchTerms?: string[]
  taxonomyCodes?: string[]
  processCodes?: string[]
  problemCodes?: string[]
  useCaseCodes?: string[]
  relatedCodes: string[]
  stageScopes: ConsultingKnowledgeEntry["stageScopes"]
  details: ConsultingKnowledgeEntry["details"]
}

const domainCode = "customer-operations"

const processes: ProcessSeed[] = [
  {
    code: "customer-inbound-support",
    title: "Eingehender Kundensupport",
    summary:
      "Kundenanfragen werden entgegengenommen, verstanden und in einen bearbeitbaren Vorgang übersetzt.",
    tags: ["support", "inbound", "service"],
    taxonomyCodes: ["email-support", "live-chat", "call-centers", "help-desk"],
    matchTerms: ["support", "kundensupport", "kundenanfrage", "kundenanfragen", "anfrage", "anfragen", "posteingang", "eingang", "hotline", "kundendienst", "service"],
  },
  {
    code: "case-management-and-triage",
    title: "Fallbearbeitung und Triage",
    summary:
      "Vorgänge werden klassifiziert, angereichert und an die richtige Bearbeitungsstufe weitergereicht.",
    tags: ["triage", "case-management", "routing"],
    taxonomyCodes: ["ticket-management", "crm", "customer-service"],
    matchTerms: ["ticket", "tickets", "triage", "vorgang", "vorgänge", "fallbearbeitung", "routing", "weiterleitung", "priorisierung", "klassifizierung", "eskalation"],
  },
  {
    code: "account-and-access-actions",
    title: "Konten- und Zugriffsaktionen",
    summary:
      "Kontenbezogene Änderungen werden nach Prüfung und Freigabe systemisch ausgeführt.",
    tags: ["identity", "access", "account"],
    taxonomyCodes: ["sales-support", "customer-service", "crm"],
    matchTerms: ["konto", "konten", "account", "zugang", "zugriff", "passwort", "freischaltung", "berechtigung", "stammdaten", "onboarding"],
  },
  {
    code: "transaction-and-dispute-resolution",
    title: "Transaktionen und Reklamationen",
    summary:
      "Rückerstattungen, Umbuchungen, Rechnungsfragen und ähnliche Vorgänge werden geprüft und korrigiert.",
    tags: ["billing", "dispute", "refund", "transaction"],
    taxonomyCodes: ["booking-reservations", "guest-communication", "ticket-management"],
    matchTerms: ["rechnung", "rechnungen", "zahlung", "zahlungen", "erstattung", "rückerstattung", "refund", "reklamation", "reklamationen", "storno", "gutschrift", "buchung"],
  },
  {
    code: "proactive-recovery-and-retention",
    title: "Proaktive Wiederherstellung und Bindung",
    summary:
      "Unterbrechungen, Kündigungen und Eskalationen werden aktiv abgefangen, bevor sie eskalieren.",
    tags: ["retention", "recovery", "proactive"],
    taxonomyCodes: ["guest-communication", "sales-support", "help-desk"],
    matchTerms: ["kündigung", "kündigungen", "rückgewinnung", "retention", "churn", "abwanderung", "proaktiv", "nachfassen", "beschwerde", "beschwerden"],
  },
]

// Every process code in the domain. The domain-wide framework and the AI
// readiness criteria are curated against all of them, because that is what they
// evaluate.
const allProcessCodes = processes.map((process) => process.code)

const taxonomyNodes: TaxonomySeed[] = [
  { code: "email-support", title: "E-Mail Support", summary: "Schriftliche Anfragebearbeitung über Posteingang und Fallsteuerung.", processCode: "customer-inbound-support", matchTerms: ["e-mail", "email", "mail", "mails", "postfach", "posteingang", "mailbox", "schriftlich"] },
  { code: "customer-service", title: "Customer Service", summary: "Allgemeine Serviceanfragen, Kontonutzung und einfache Änderungen.", processCode: "account-and-access-actions", matchTerms: ["kundenservice", "customer service", "serviceanfrage", "serviceanfragen", "kundenbetreuung"] },
  { code: "call-centers", title: "Call Centers", summary: "Telefonische Interaktion mit strukturierter Gesprächsführung und Eskalation.", processCode: "customer-inbound-support", matchTerms: ["call center", "callcenter", "telefon", "telefonie", "hotline", "anruf", "anrufe", "telefonisch"] },
  { code: "live-chat", title: "Live Chat", summary: "Schnelle dialogische Unterstützung für Standardanliegen.", processCode: "case-management-and-triage", matchTerms: ["chat", "live chat", "livechat", "messenger", "whatsapp", "chatbot"] },
  { code: "help-desk", title: "Help Desk", summary: "Technische und operative Anfragen mit Priorisierung und Übergabe.", processCode: "case-management-and-triage", matchTerms: ["helpdesk", "help desk", "servicedesk", "service desk", "it-support"] },
  { code: "crm", title: "CRM", summary: "Kunden- und Vorgangsdaten als Kontext für Service und Bindung.", processCode: "account-and-access-actions", matchTerms: ["crm", "salesforce", "hubspot", "kundendaten", "kundenakte"] },
  { code: "ticket-management", title: "Ticket Management", summary: "Erfassung, Zuordnung und Lebenszyklussteuerung von Vorgängen.", processCode: "case-management-and-triage", matchTerms: ["ticketsystem", "ticketsysteme", "zendesk", "jira", "freshdesk", "otrs", "ticketing"] },
  { code: "booking-reservations", title: "Booking & Reservations", summary: "Termin-, Reise- und Buchungsänderungen mit Verfügbarkeitsprüfung.", processCode: "transaction-and-dispute-resolution", matchTerms: ["buchung", "buchungen", "reservierung", "reservierungen", "termin", "termine", "booking"] },
  { code: "guest-communication", title: "Guest Communication", summary: "Gastbezogene Kommunikation vor, während und nach einem Vorgang.", processCode: "proactive-recovery-and-retention", matchTerms: ["gast", "gäste", "gastkommunikation", "guest", "aufenthalt"] },
  { code: "sales-support", title: "Sales Support", summary: "Vertriebsunterstützung, Angebotsfragen und Rückgewinnung.", processCode: "proactive-recovery-and-retention", matchTerms: ["vertrieb", "sales", "angebot", "angebote", "upsell", "vertriebsunterstützung"] },
]

const aiReadinessCriteria: GenericSeed[] = [
  {
    code: "structured-inputs",
    kind: "ai_readiness_criterion",
    title: "Strukturierte Eingangsdaten",
    summary:
      "Das Problem liefert wiederkehrende, ausreichend strukturierte Eingaben, die maschinell verarbeitet werden können.",
    tags: ["data", "inputs"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Bewerten, ob das Problem eine verlässliche KI-Vorverarbeitung trägt.",
      applicability: ["Wiederkehrende Fälle", "Klare Datenspalten oder Formularfelder"],
      questions: ["Welche Felder sind heute schon standardisiert erfasst?"],
      criteria: ["Eingaben sind wiederholbar und vergleichbar."],
      signals: ["Formulare", "Ticketfelder", "Systemdaten"],
      steps: ["Eingabestruktur prüfen", "fehlende Felder als Lücke markieren"],
      risks: ["Freitext ohne Struktur"],
      mitigations: ["Pflichtfelder und Formularlogik"],
      roiDrivers: ["Schnellere Klassifikation"],
      bestPractices: ["Erst strukturieren, dann automatisieren"],
      notes: ["Grundvoraussetzung für spätere Filterung und Matching."],
    }),
  },
  {
    code: "system-of-record-access",
    kind: "ai_readiness_criterion",
    title: "Systemzugriff auf die führende Quelle",
    summary:
      "Die KI kann die führende Systemquelle verlässlich lesen und, wenn erlaubt, Änderungen sicher vorbereiten.",
    tags: ["integration", "system"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Prüfen, ob der relevante Prozess an ein System of Record angebunden ist.",
      applicability: ["Live-Status", "Buchungen", "Kontodaten"],
      questions: ["Welches System ist die führende Quelle?"],
      criteria: ["Lesender Zugriff ist möglich."],
      signals: ["API", "Backend", "Schreibschutz"],
      steps: ["Zugriffsart klären", "Integrationsgrenzen dokumentieren"],
      risks: ["Manuelle Datensilos"],
      mitigations: ["API- oder Backend-Anbindung"],
      roiDrivers: ["Weniger Medienbrüche"],
      bestPractices: ["Nur auf stabile Systeme schreiben"],
      notes: ["Read-first ist der sichere Ausgangspunkt."],
    }),
  },
  {
    code: "identity-verification",
    kind: "ai_readiness_criterion",
    title: "Identitäts- und Berechtigungsprüfung",
    summary:
      "Der Prozess verlangt eine belastbare Identitätsprüfung, bevor eine Konten- oder Transaktionsänderung ausgelöst wird.",
    tags: ["identity", "security"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Sicherstellen, dass nur berechtigte Personen schreibende Aktionen auslösen.",
      applicability: ["Kontenänderungen", "Zugriff", "Rückerstattungen"],
      questions: ["Wie wird heute legitimiert?"],
      criteria: ["Identität und Berechtigung sind prüfbar."],
      signals: ["MFA", "Verifikationsdaten", "Freigabeprozess"],
      steps: ["Legitimation dokumentieren", "Freigabegrenze definieren"],
      risks: ["Falsche Freigabe"],
      mitigations: ["Zweistufige Kontrolle"],
      roiDrivers: ["Weniger Betrugs- und Fehlerfälle"],
      bestPractices: ["Keine schreibende Aktion ohne Authentisierung"],
      notes: ["Zentral für riskantere Kundenaktionen."],
    }),
  },
  {
    code: "exception-rate",
    kind: "ai_readiness_criterion",
    title: "Hohe Ausnahmerate",
    summary:
      "Je häufiger ein Vorgang vom Standard abweicht, desto wichtiger sind Triage, Priorisierung und Eskalation.",
    tags: ["exceptions", "triage"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Bewerten, ob der Prozess viele Sonderfälle erzeugt.",
      applicability: ["Support", "Triage", "Case Management"],
      questions: ["Wie oft wird manuell eskaliert?"],
      criteria: ["Ausnahmen sind häufig genug für Automatisierungsschritte."],
      signals: ["Escalation", "Sonderfälle", "Abbrüche"],
      steps: ["Ausnahmetypen bündeln", "Eskalationspfad planen"],
      risks: ["Zu komplexe Einzelfälle"],
      mitigations: ["Human-in-the-loop"],
      roiDrivers: ["Entlastung des Second-Level-Supports"],
      bestPractices: ["Erst triagieren, dann lösen"],
      notes: ["Die Ausnahmerate bestimmt die passende Automatisierungsstufe."],
    }),
  },
  {
    code: "customer-impact",
    kind: "ai_readiness_criterion",
    title: "Messbarer Kundennutzen",
    summary:
      "Das Vorhaben muss einen klaren Effekt auf Aufwand, Geschwindigkeit, Qualität oder Umsatz haben.",
    tags: ["roi", "value"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Wertbeitrag und Erfolgskriterien sichtbar machen.",
      applicability: ["Alle Customer-Operations-Anwendungsfälle"],
      questions: ["Welche Kennzahl verbessert sich messbar?"],
      criteria: ["Vorher / nachher ist definiert."],
      signals: ["AHT", "Conversion", "Retention", "CSAT"],
      steps: ["Baseline festhalten", "Zielwerte festlegen"],
      risks: ["Wert nur gefühlt statt gemessen"],
      mitigations: ["Klare ROI-Logik"],
      roiDrivers: ["Weniger Bearbeitungszeit", "mehr Abschlussrate"],
      bestPractices: ["Messgrößen vor Lösung wählen"],
      notes: ["An den Discovery-Baseline-Ansatz anschließen."],
    }),
  },
  {
    code: "human-approval-boundary",
    kind: "ai_readiness_criterion",
    title: "Menschliche Freigabegrenze",
    summary:
      "Wenn der Prozess risikoreiche Seiteneffekte hat, braucht er eine klare Freigabe- oder Eskalationsgrenze.",
    tags: ["approval", "human-in-the-loop"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["discovery", "assessment"],
    details: detailsOf({
      objective: "Bestimmen, wo ein Mensch die finale Entscheidung behält.",
      applicability: ["Refund", "Unlock", "Rebooking", "Retention"],
      questions: ["Welche Schritte dürfen nie autonom abschließen?"],
      criteria: ["Freigabeweg ist klar beschrieben."],
      signals: ["Approve", "Reject", "Hold"],
      steps: ["Freigabeschwelle bestimmen", "Eskalationsweg dokumentieren"],
      risks: ["Autonomie ohne Kontrollpunkt"],
      mitigations: ["Explizite Freigabelogik"],
      roiDrivers: ["Schnellerer Durchlauf ohne Kontrollverlust"],
      bestPractices: ["Autonomie an Risiko koppeln"],
      notes: ["Passt zu den roten-Flag-Prozessen im Use-Case-Set."],
    }),
  },
  {
    code: "latency-tolerance",
    kind: "ai_readiness_criterion",
    title: "Latenztoleranz",
    summary:
      "Der Prozess muss schnell genug sein, damit dialogische oder operative Nutzung sinnvoll bleibt.",
    tags: ["latency", "experience"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["assessment"],
    details: detailsOf({
      objective: "Erkennen, ob die Reaktionszeit ein Nutzungshindernis ist.",
      applicability: ["Chat", "Call Center", "Proaktive Benachrichtigung"],
      questions: ["Wie schnell muss geantwortet werden?"],
      criteria: ["Antwortfenster ist geschäftlich akzeptabel."],
      signals: ["Live chat", "Sofortantwort", "SLA"],
      steps: ["Latenzbudget festlegen", "Fallbacks planen"],
      risks: ["Zu langsame Antwort zerstört den Nutzen"],
      mitigations: ["Caching und Vorverarbeitung"],
      roiDrivers: ["Weniger Wartezeit", "höhere Zufriedenheit"],
      bestPractices: ["Zeitkritische Pfade von Batch trennen"],
      notes: ["Besonders wichtig für Chat und Voice."],
    }),
  },
  {
    code: "regulatory-exposure",
    kind: "ai_readiness_criterion",
    title: "Regulatorisches Risiko",
    summary:
      "Je sensibler der Vorgang, desto stärker müssen Compliance, Protokollierung und Freigaben ausfallen.",
    tags: ["compliance", "risk"],
    relatedCodes: ["customer-operations-readiness-framework"],
    stageScopes: ["assessment"],
    details: detailsOf({
      objective: "Sicherheits- und Compliance-Aufwand früh sichtbar machen.",
      applicability: ["Zahlungen", "Versicherung", "Banking-nahe Prozesse"],
      questions: ["Welche Regeln oder Richtlinien gelten?"],
      criteria: ["Risikograd ist bekannt."],
      signals: ["GDPR", "MFA", "Audit", "Approval"],
      steps: ["Risikoklasse bestimmen", "Kontrollpunkte festlegen"],
      risks: ["Nicht konforme Automatisierung"],
      mitigations: ["Freigaben und Audit-Trail"],
      roiDrivers: ["Vermeidung von Fehlentscheidungen"],
      bestPractices: ["Regulatorische Grenzen zuerst klären"],
      notes: ["Besonders relevant für Karten, Zahlungen und Kundendaten."],
    }),
  },
]

const discoveryQuestions: GenericSeed[] = [
  questionSeed(
    "support-volume-question",
    "Wie häufig tritt dieser Vorgang auf?",
    "Die Häufigkeit entscheidet, ob ein wiederholbarer Automatisierungsfall vorliegt.",
    ["discovery"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["customer-operations-readiness-framework"],
    ["Wiederkehrende Fälle", "Volumen bekannt?"],
  ),
  questionSeed(
    "process-breaks-question",
    "Wo bricht der aktuelle Prozess heute typischerweise ab?",
    "Die Engstelle zeigt, wo Triage oder Automatisierung am meisten Entlastung bringt.",
    ["discovery"],
    ["case-management-and-triage", "transaction-and-dispute-resolution"],
    ["customer-operations-readiness-framework"],
    ["Bottleneck sichtbar?", "Bearbeitung stoppt?"],
  ),
  questionSeed(
    "approval-question",
    "Wer muss eine risikoreiche Aktion freigeben?",
    "Freigabepunkte bestimmen, ob der Vorgang komplett, teilautomatisch oder nur assistiert laufen kann.",
    ["discovery", "assessment"],
    ["account-and-access-actions", "transaction-and-dispute-resolution", "proactive-recovery-and-retention"],
    ["customer-operations-readiness-framework"],
    ["Menschliche Freigabe?"],
  ),
  questionSeed(
    "measurement-question",
    "Woran würde der Kunde Erfolg messen?",
    "Die Erfolgskennzahl macht den Use Case wirtschaftlich und operativ prüfbar.",
    ["discovery", "assessment"],
    ["transaction-and-dispute-resolution", "proactive-recovery-and-retention"],
    ["customer-operations-readiness-framework"],
    ["Kennzahl", "Messmethode", "Baseline"],
  ),
]

const assessmentFramework: GenericSeed = {
  code: "customer-operations-readiness-framework",
  kind: "assessment_framework",
  title: "Customer-Operations-Readiness Framework",
  summary:
    "Ein deterministischer Bewertungsrahmen für Kundensupport- und Operations-Prozesse in Customer Operations.",
  tags: ["framework", "assessment", "customer-operations"],
  relatedCodes: [
    "structured-inputs",
    "system-of-record-access",
    "identity-verification",
    "exception-rate",
    "customer-impact",
    "human-approval-boundary",
    "latency-tolerance",
    "regulatory-exposure",
  ],
  stageScopes: ["assessment"],
  details: detailsOf({
    objective:
      "Konsistent prüfen, ob ein Customer-Operations-Prozess für KI geeignet ist.",
    applicability: [
      "Eingehender Support",
      "Fallbearbeitung",
      "Kontoaktionen",
      "Reklamationen",
      "Wiederherstellung",
    ],
    questions: [
      "Ist das Eingabematerial strukturiert?",
      "Ist die führende Systemquelle erreichbar?",
      "Braucht der Prozess Identitätsprüfung?",
    ],
    criteria: [
      "Volumen oder Wiederholung rechtfertigt Automatisierung.",
      "Die Risiko- und Freigabekette ist klar.",
      "Ein messbarer Nutzen liegt vor.",
    ],
    signals: ["Volume", "Approval", "Audit", "Integration", "Latency"],
    steps: [
      "Prozess identifizieren",
      "Risiko- und Nutzenlage bewerten",
      "KI-Reife prüfen",
    ],
    risks: ["Autonomie ohne Kontrolle", "Einzelfalllastigkeit"],
    mitigations: ["Human-in-the-loop", "Stufenweise Einführung"],
    roiDrivers: ["Bearbeitungszeit", "Deflection", "Konversion", "Fehlerreduktion"],
    bestPractices: ["Deterministisch prüfen", "Freigabegrenzen dokumentieren"],
    notes: ["Wird durch den Workbench-Assessment-Schritt genutzt."],
  }),
}

const solutionPatterns: GenericSeed[] = [
  genericSeed(
    "verified-exception-resolution",
    "solution_pattern",
    "Verifizierte Ausnahmelösung",
    "Ein problematischer Einzelfall wird geprüft, freigegeben und systemisch abgeschlossen.",
    ["exception", "approval", "resolution"],
    ["transaction-and-dispute-resolution", "account-and-access-actions"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Risikoreiche Aktionen mit expliziter Freigabe kontrolliert ausführen.",
      applicability: ["Retouren", "Umbuchungen", "Freischaltungen", "Rückerstattungen"],
      questions: ["Welche Freigabe ist nötig?", "Welche Daten müssen vorliegen?"],
      criteria: ["Prüfung vor Ausführung", "Auditierbarer Abschluss"],
      signals: ["Approval", "Hold", "Reject"],
      steps: ["Fall anreichern", "Freigabe einholen", "Aktion ausführen"],
      risks: ["Falsche Autorisierung"],
      mitigations: ["Identitätsprüfung und Audit-Trail"],
      roiDrivers: ["Weniger manuelle Bearbeitung"],
      bestPractices: ["Erst verifizieren, dann handeln"],
      notes: ["Passt zu Transaktionen mit schreibender Wirkung."],
    },
  ),
  genericSeed(
    "status-and-triage-assistance",
    "solution_pattern",
    "Status- und Triage-Unterstützung",
    "Die KI erklärt den aktuellen Fallstand, fragt fehlende Informationen ab und ordnet den Vorgang ein.",
    ["status", "triage", "support"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["discovery", "assessment", "prioritization", "solution_matching", "roadmap"],
    {
      objective: "Wiederkehrende Anfragen schneller einordnen und beantworten.",
      applicability: ["Statusabfragen", "Help Desk", "Ticket-Triage", "Guest Communication"],
      questions: ["Welche Information fehlt noch?", "Wer muss den Fall sehen?"],
      criteria: ["Triage ist reproduzierbar"],
      signals: ["Missing data", "Priority", "Route"],
      steps: ["Fall klassifizieren", "fehlende Angaben abfragen", "an Zielteam routen"],
      risks: ["Falsche Zuordnung"],
      mitigations: ["Klare Kategorien und Eskalation"],
      roiDrivers: ["AHT", "First-contact resolution"],
      bestPractices: ["Struktur vor Antwort"],
      notes: ["Die passende Form für hohe Anfragevolumina."],
    },
  ),
  genericSeed(
    "read-only-explanation",
    "solution_pattern",
    "Read-only Erklärung",
    "Die KI liest Systeme nur aus, erklärt Abweichungen und bereitet bei Bedarf eine menschliche Freigabe vor.",
    ["read-only", "billing", "explanation"],
    ["customer-inbound-support", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching"],
    {
      objective: "Sensible Informationen erklären, ohne sie autonom zu verändern.",
      applicability: ["Rechnungsfragen", "Statusklärung", "Abgleich"],
      questions: ["Welche Daten dürfen nur gelesen werden?", "Welche Erklärung braucht der Kunde?"],
      criteria: ["Kein Schreibzugriff erforderlich"],
      signals: ["Read only", "Compare", "Explain"],
      steps: ["Lesend auswerten", "Abweichung erklären", "Freigabe pfaden"],
      risks: ["Überschreitung in schreibende Aktionen"],
      mitigations: ["Klare Schreibgrenzen"],
      roiDrivers: ["Weniger Telefonkontakte"],
      bestPractices: ["Nur lesend starten"],
      notes: ["Gut für Billing und ähnliche Auskunftsfälle."],
    },
  ),
  genericSeed(
    "proactive-recovery",
    "solution_pattern",
    "Proaktive Wiederherstellung",
    "Die KI erkennt Unterbrechungen früh, schlägt Alternativen vor und stößt die nächste sinnvolle Aktion an.",
    ["proactive", "recovery", "retention"],
    // The processes this pattern realizes. It reaches booking, guest, and sales
    // work through those processes' own taxonomy nodes rather than naming them
    // here, where only process codes belong.
    ["proactive-recovery-and-retention", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Ausfälle und Kündigungsimpulse aktiv abfangen.",
      applicability: ["Ausfall", "Kündigung", "Retention", "Rebooking"],
      questions: ["Welche Alternativen sind verfügbar?", "Was ist der nächste beste Schritt?"],
      criteria: ["Alternative oder Gegenangebot ist systemisch darstellbar"],
      signals: ["Alternative", "Rebook", "Save offer"],
      steps: ["Ereignis erkennen", "Optionen prüfen", "Kundenkontakt auslösen"],
      risks: ["Falsches Gegenangebot"],
      mitigations: ["Freigabegrenzen und Templates"],
      roiDrivers: ["Save rate", "Umsatzsicherung"],
      bestPractices: ["Proaktiv statt reaktiv arbeiten"],
      notes: ["Passt zu Travel, Retention und ähnlichen Abläufen."],
    },
  ),
  genericSeed(
    "incident-dossier",
    "solution_pattern",
    "Strukturiertes Dossier",
    "Die KI baut aus einem unstrukturierten Ereignis einen prüfbaren Fallbericht für den Menschen.",
    ["dossier", "incident", "structured-intake"],
    ["case-management-and-triage", "customer-inbound-support"],
    ["discovery", "assessment", "solution_matching", "roadmap"],
    {
      objective: "Aus einem Ereignis ein belastbares, strukturiertes Dossier machen.",
      applicability: ["FNOL", "Ticket-Intake", "Beschwerde", "Supportfall"],
      questions: ["Welche Pflichtdaten fehlen noch?", "Welche Anhänge müssen angefordert werden?"],
      criteria: ["Fall ist vollständig genug für die Fachprüfung"],
      signals: ["Forms", "attachments", "required fields"],
      steps: ["Daten sammeln", "Fehlendes ergänzen", "an Sachbearbeitung geben"],
      risks: ["Unvollständiger Vorgang"],
      mitigations: ["Pflichtfelder und Follow-up"],
      roiDrivers: ["Weniger Nacharbeit"],
      bestPractices: ["Vorprüfung vor Weitergabe"],
      notes: ["Hilft bei Versicherungs- und Schadensfällen."],
    },
  ),
  genericSeed(
    "transaction-safe-action",
    "solution_pattern",
    "Transaktionssichere Aktion",
    "Die KI bereitet eine Änderung vor, führt sie mit Kontrolle aus und protokolliert den Vorgang.",
    ["transaction", "safe-action", "control"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Schreibende Kundenvorgänge sicher und nachvollziehbar ausführen.",
      applicability: ["Adressänderung", "Kontoänderung", "Entsperrung", "Buchung"],
      questions: ["Welche Prüfung braucht die Aktion?", "Welche Rückmeldung muss gespeichert werden?"],
      criteria: ["Aktion ist reversibel oder kontrolliert"],
      signals: ["Write", "Confirm", "Audit"],
      steps: ["Berechtigung prüfen", "Änderung vorbereiten", "Änderung ausführen"],
      risks: ["Fehlkonfiguration"],
      mitigations: ["Zweistufige Prüfung"],
      roiDrivers: ["Weniger manuelle Eingriffe"],
      bestPractices: ["Jede Schreibaktion auditieren"],
      notes: ["Wichtig für alles mit systemischer Änderung."],
    },
  ),
]

const implementationPatterns: GenericSeed[] = [
  genericSeed(
    "read-first-then-act",
    "implementation_pattern",
    "Zuerst lesen, dann handeln",
    "Die Lösung liest die führende Quelle zunächst nur aus und baut erst dann eine Aktion auf.",
    ["read-first", "safety"],
    ["customer-inbound-support", "transaction-and-dispute-resolution"],
    ["roadmap"],
    {
      objective: "Sichere Ausgangsbasis für jede Verarbeitung.",
      applicability: ["Support", "Billing", "Case Management"],
      questions: ["Was ist die führende Quelle?", "Welche Daten werden benötigt?"],
      criteria: ["Leseschritt kommt vor jeder Schreibaktion"],
      signals: ["Read only", "Check", "Prepare"],
      steps: ["Lesen", "Validieren", "Handeln"],
      risks: ["Direkt auf eine Aktion springen"],
      mitigations: ["Expliziter Vorbereitungsstatus"],
      roiDrivers: ["Weniger Fehler"],
      bestPractices: ["Read-first als Standard"],
      notes: ["Basis für sichere Integrationen."],
    },
  ),
  genericSeed(
    "human-approval-gate",
    "implementation_pattern",
    "Freigabeschritt mit Mensch",
    "Ein risikoreicher Schritt läuft nur bis zur Freigabe und wird erst danach finalisiert.",
    ["approval", "human-in-the-loop"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["roadmap"],
    {
      objective: "Risikoreiche Aktionen nicht autonom abschließen.",
      applicability: ["Refund", "Unlock", "Rebooking", "Retention"],
      questions: ["Wer gibt frei?", "Was wird protokolliert?"],
      criteria: ["Freigabe ist eindeutig"],
      signals: ["Approve", "Hold", "Reject"],
      steps: ["Entwurf", "Freigabe", "Ausführung"],
      risks: ["Autonome Ausführung ohne Kontrolle"],
      mitigations: ["Explizite Freigabelogik"],
      roiDrivers: ["Schnellerer Durchlauf mit Kontrolle"],
      bestPractices: ["Freigabe nicht verstecken"],
      notes: ["Passt zu kritischen Konten- und Zahlungsfällen."],
    },
  ),
  genericSeed(
    "structured-intake",
    "implementation_pattern",
    "Strukturierter Intake",
    "Freitext wird zu stabilen Feldern, damit Folgeschritte verlässlich arbeiten können.",
    ["intake", "structure"],
    ["case-management-and-triage"],
    ["discovery", "assessment"],
    {
      objective: "Unstrukturierten Eingang für Triage nutzbar machen.",
      applicability: ["Ticket", "FNOL", "Beschwerde"],
      questions: ["Welche Felder sind Pflicht?", "Welche Belege fehlen?"],
      criteria: ["Intake ist wiederholbar"],
      signals: ["Fields", "attachments", "priority"],
      steps: ["Intake strukturieren", "Pflichtdaten prüfen", "weiterleiten"],
      risks: ["Freitext bleibt unbrauchbar"],
      mitigations: ["Pflichtfelder und Templates"],
      roiDrivers: ["Weniger Nacharbeit"],
      bestPractices: ["Eingang standardisieren"],
      notes: ["Nützlich für jede vorgelagerte Erfassung."],
    },
  ),
  genericSeed(
    "proactive-workflow",
    "implementation_pattern",
    "Proaktiver Workflow",
    "Ein Ereignis triggert Folgeaktionen und benachrichtigt die richtige Stelle ohne manuelles Nachfassen.",
    ["proactive", "workflow"],
    ["proactive-recovery-and-retention", "customer-inbound-support"],
    ["roadmap"],
    {
      objective: "Reaktion auf Ereignisse beschleunigen.",
      applicability: ["Ausfall", "Kündigung", "Eskalation"],
      questions: ["Welches Ereignis löst was aus?"],
      criteria: ["Trigger und Folgeaktion sind definiert"],
      signals: ["Event", "trigger", "notification"],
      steps: ["Ereignis erkennen", "Aktion vorbereiten", "Menschen informieren"],
      risks: ["Überreaktion"],
      mitigations: ["Schwellenwerte und Freigaben"],
      roiDrivers: ["Weniger Verzögerung"],
      bestPractices: ["Nur klare Trigger automatisieren"],
      notes: ["Besonders relevant für Recovery und Retention."],
    },
  ),
  genericSeed(
    "audit-every-change",
    "implementation_pattern",
    "Jede Änderung auditieren",
    "Jede schreibende Aktion und jeder relevante Übergang bekommt ein nachvollziehbares Protokoll.",
    ["audit", "traceability"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["roadmap"],
    {
      objective: "Nachvollziehbarkeit und Review sichern.",
      applicability: ["Alle Schreibaktionen"],
      questions: ["Was muss protokolliert werden?"],
      criteria: ["Der Vorgang ist später rekonstruierbar"],
      signals: ["Audit", "event", "history"],
      steps: ["Aktion ausführen", "Protokoll schreiben", "Nachverfolgbarkeit prüfen"],
      risks: ["Unklare Verantwortlichkeit"],
      mitigations: ["Eindeutige Identität und Zeitstempel"],
      roiDrivers: ["Weniger Kontrollverluste"],
      bestPractices: ["Audit als Pflichtschritt"],
      notes: ["Unterstützt die Governance-Erwartung des Produkts."],
    },
  ),
  genericSeed(
    "fallback-and-escalation",
    "implementation_pattern",
    "Fallback und Eskalation",
    "Wenn die Automatisierung an ihre Grenze stößt, übernimmt ein klar benannter menschlicher Pfad.",
    ["fallback", "escalation"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["assessment", "roadmap"],
    {
      objective: "Sicherstellen, dass schwierige Fälle nicht verloren gehen.",
      applicability: ["Unklare Fälle", "Sonderfälle", "Sicherheitsgrenzen"],
      questions: ["Wer übernimmt den Sonderfall?"],
      criteria: ["Eskalation ist sichtbar und erreichbar"],
      signals: ["Escalate", "handoff", "manual review"],
      steps: ["Grenze erkennen", "Fallback aktivieren", "Mensch informieren"],
      risks: ["Stillstand ohne Zuständigkeit"],
      mitigations: ["Benannter Eskalationspfad"],
      roiDrivers: ["Weniger offene Fälle"],
      bestPractices: ["Grenzen explizit bauen"],
      notes: ["Nützlich bei komplexen Ausnahmen."],
    },
  ),
]

const roiModels: GenericSeed[] = [
  genericSeed(
    "aht-reduction",
    "roi_model",
    "AHT-Reduktion",
    "Wert entsteht durch kürzere Bearbeitungszeiten pro Fall.",
    ["aht", "efficiency"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["assessment", "prioritization"],
    {
      objective: "Zeit pro Fall messen und senken.",
      applicability: ["Support", "Triage", "Read-only explanation"],
      questions: ["Wie lange dauert der Vorgang heute?"],
      criteria: ["Zeitersparnis ist plausibel"],
      signals: ["Duration", "handle time"],
      steps: ["Baseline erfassen", "Zielwert setzen"],
      risks: ["Zeitersparnis ohne Qualitätsgewinn"],
      mitigations: ["Qualitätskontrolle"],
      roiDrivers: ["Mehr Durchsatz"],
      bestPractices: ["Zeit und Qualität zusammen betrachten"],
      notes: ["Am besten messbar in hochvolumigen Prozessen."],
    },
  ),
  genericSeed(
    "deflection-model",
    "roi_model",
    "Deflection-Modell",
    "Wert entsteht, wenn wiederkehrende Anfragen ohne menschliche Bearbeitung gelöst werden.",
    ["deflection", "self-service"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["assessment", "prioritization"],
    {
      objective: "Wie viele Fälle werden vom Team weggenommen?",
      applicability: ["Chat", "Support", "FAQ", "Statusfragen"],
      questions: ["Welche Fälle können vollständig beantwortet werden?"],
      criteria: ["Selbstbedienungsquote ist messbar"],
      signals: ["Containment", "deflection"],
      steps: ["Deflection-Ziel bestimmen", "Verlauf messen"],
      risks: ["Falsche Antwort statt echter Lösung"],
      mitigations: ["Fallback und Qualitätssicherung"],
      roiDrivers: ["Weniger Ticketvolumen"],
      bestPractices: ["Nur geeignete Fälle deflektieren"],
      notes: ["Gut für volumengetriebene Anfragen."],
    },
  ),
  genericSeed(
    "retention-uplift",
    "roi_model",
    "Retention-Uplift",
    "Wert entsteht durch gerettete Kundenbeziehungen oder vermiedene Kündigungen.",
    ["retention", "revenue"],
    ["proactive-recovery-and-retention"],
    ["assessment", "prioritization"],
    {
      objective: "Rückgewinnung monetär bewerten.",
      applicability: ["Kündigung", "Angebot", "Proaktive Kontaktaufnahme"],
      questions: ["Wie viele Kunden werden heute verloren?"],
      criteria: ["Save rate ist sichtbar"],
      signals: ["Conversion", "save rate"],
      steps: ["Baseline setzen", "Angebot messen"],
      risks: ["Zu aggressives Angebot"],
      mitigations: ["Freigabegrenzen"],
      roiDrivers: ["Mehr Erhalt von Umsatz"],
      bestPractices: ["Retention mit Freigabe steuern"],
      notes: ["Besonders relevant bei Abos und Reise."],
    },
  ),
  genericSeed(
    "error-rework-reduction",
    "roi_model",
    "Fehler- und Nacharbeitsreduktion",
    "Wert entsteht, wenn Korrekturen, Rückfragen und Nacharbeit sinken.",
    ["rework", "quality"],
    ["transaction-and-dispute-resolution", "case-management-and-triage"],
    ["assessment", "prioritization"],
    {
      objective: "Nacharbeit und Fehlerkosten senken.",
      applicability: ["Reklamation", "Dossier", "Support"],
      questions: ["Wie oft muss ein Fall erneut bearbeitet werden?"],
      criteria: ["Fehlerfolgen sind beobachtbar"],
      signals: ["Rework", "correction", "error"],
      steps: ["Fehlerkosten erfassen", "Ziel setzen"],
      risks: ["Falsche Messung der Nacharbeit"],
      mitigations: ["Klare Fehlerdefinition"],
      roiDrivers: ["Weniger doppelte Arbeit"],
      bestPractices: ["Fehlerkosten mitmessen"],
      notes: ["Nützlich bei operativem Chaos."],
    },
  ),
  genericSeed(
    "recovery-cost-avoidance",
    "roi_model",
    "Vermeidbare Wiederherstellungskosten",
    "Wert entsteht, wenn Proaktive Aktionen teure Folgeprozesse vermeiden.",
    ["recovery", "avoidance"],
    ["proactive-recovery-and-retention", "transaction-and-dispute-resolution"],
    ["assessment", "prioritization"],
    {
      objective: "Teure Folgeaktionen vermeiden.",
      applicability: ["Ausfall", "Umbuchung", "Eskalation"],
      questions: ["Welche Kosten entstehen ohne Intervention?"],
      criteria: ["Folgekosten sind bekannt oder schätzbar"],
      signals: ["Dispatch", "manual recovery"],
      steps: ["Folgekosten schätzen", "Alternative vergleichen"],
      risks: ["Unterschätzte Folgekosten"],
      mitigations: ["Konservative Annahmen"],
      roiDrivers: ["Vermeidbare Servicekosten"],
      bestPractices: ["Auch Gegenkosten berücksichtigen"],
      notes: ["Passt zu Wiederherstellungs- und Reiseprozessen."],
    },
  ),
]

const riskModels: GenericSeed[] = [
  genericSeed(
    "identity-risk",
    "risk_model",
    "Identitätsrisiko",
    "Die KI könnte die falsche Person oder den falschen Fall bedienen, wenn Legitimation fehlt.",
    ["identity", "security"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["assessment", "prioritization"],
    {
      objective: "Identitäts- und Berechtigungsrisiko sichtbar machen.",
      applicability: ["Unlock", "Refund", "Sensitive account data"],
      questions: ["Wie wird die Person geprüft?"],
      criteria: ["Identitätsprüfung ist zwingend"],
      signals: ["MFA", "verification", "auth"],
      steps: ["Verifikation prüfen", "Freigabe beschränken"],
      risks: ["Unberechtigte Aktion"],
      mitigations: ["MFA und Audit"],
      roiDrivers: ["Schadensvermeidung"],
      bestPractices: ["Keine schreibende Aktion ohne Legitimation"],
      notes: ["Ein Kernrisiko in account-nahen Fällen."],
    },
  ),
  genericSeed(
    "transaction-risk",
    "risk_model",
    "Transaktionsrisiko",
    "Schreibende Aktionen können Kosten, Buchungen oder Kundenerwartungen falsch verändern.",
    ["transaction", "write"],
    ["transaction-and-dispute-resolution", "account-and-access-actions"],
    ["assessment", "solution_matching"],
    {
      objective: "Fehler bei schreibenden Aktionen begrenzen.",
      applicability: ["Refund", "Rebooking", "Address changes"],
      questions: ["Welche Änderung darf wirklich passieren?"],
      criteria: ["Schreibpfad ist eng begrenzt"],
      signals: ["Write", "confirm", "rollback"],
      steps: ["Änderung vorbereiten", "prüfen", "ausführen"],
      risks: ["Falscher Schreibzustand"],
      mitigations: ["Zweistufige Ausführung"],
      roiDrivers: ["Weniger Korrekturen"],
      bestPractices: ["Vor dem Schreiben validieren"],
      notes: ["Wichtig für alles mit Systemänderung."],
    },
  ),
  genericSeed(
    "compliance-risk",
    "risk_model",
    "Compliance-Risiko",
    "Regulatorische Vorgaben, Datenschutz und Aufbewahrung können den Prozess begrenzen.",
    ["compliance", "privacy"],
    ["customer-inbound-support", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching"],
    {
      objective: "Regulatorische Grenzen früh erfassen.",
      applicability: ["Billing", "Insurance", "Payments", "Identity"],
      questions: ["Welche Vorgaben gelten?"],
      criteria: ["Pflichtkontrollen sind vorhanden"],
      signals: ["GDPR", "audit", "approval"],
      steps: ["Regeln erfassen", "Kontrollen dokumentieren"],
      risks: ["Nicht konforme Automatisierung"],
      mitigations: ["Audit-Trail und Freigaben"],
      roiDrivers: ["Vermeidbare Strafen und Fehler"],
      bestPractices: ["Compliance zuerst prüfen"],
      notes: ["Besonders wichtig bei sensiblen Kundendaten."],
    },
  ),
  genericSeed(
    "trust-risk",
    "risk_model",
    "Vertrauensrisiko",
    "Eine falsche oder zu selbstsichere Antwort kann Kund:innen und Teams Vertrauen kosten.",
    ["trust", "experience"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["assessment", "solution_matching"],
    {
      objective: "Vertrauen und Erklärbarkeit schützen.",
      applicability: ["Antworten", "Erklärungen", "Recommendations"],
      questions: ["Wie sichtbar ist Unsicherheit?"],
      criteria: ["Unsicherheit ist benannt"],
      signals: ["uncertainty", "explainability"],
      steps: ["Unsicherheit markieren", "Fallback anbieten"],
      risks: ["Zu selbstsichere Falschantwort"],
      mitigations: ["Transparente Darstellung"],
      roiDrivers: ["Weniger Eskalation"],
      bestPractices: ["Unsicherheit sichtbar halten"],
      notes: ["Zentral für assistive Systeme."],
    },
  ),
  genericSeed(
    "integration-risk",
    "risk_model",
    "Integrationsrisiko",
    "Schwache oder instabile Systeme erschweren zuverlässige Automatisierung.",
    ["integration", "operations"],
    ["customer-inbound-support", "transaction-and-dispute-resolution"],
    ["assessment"],
    {
      objective: "Integrationsfähigkeit und Ausfallsicherheit bewerten.",
      applicability: ["API", "Backend", "Legacy"],
      questions: ["Wie stabil ist der Systemzugriff?"],
      criteria: ["Integration ist wiederholbar"],
      signals: ["API", "timeout", "legacy"],
      steps: ["Systeme prüfen", "Fallback definieren"],
      risks: ["Fehlerhafte Schnittstellen"],
      mitigations: ["Read-first und Fallback"],
      roiDrivers: ["Weniger manuelle Handoffs"],
      bestPractices: ["Schnittstellen vor der Automatisierung prüfen"],
      notes: ["Besonders relevant bei Legacy-Systemen."],
    },
  ),
  genericSeed(
    "latency-risk",
    "risk_model",
    "Latenzrisiko",
    "Zu langsame Reaktion macht dialogische oder operative Flows unbrauchbar.",
    ["latency", "experience"],
    ["customer-inbound-support", "proactive-recovery-and-retention"],
    ["assessment"],
    {
      objective: "Reaktionszeit als Risiko bewerten.",
      applicability: ["Chat", "Voice", "Proactive outreach"],
      questions: ["Wie viel Zeit ist akzeptabel?"],
      criteria: ["Antworten kommen rechtzeitig"],
      signals: ["SLA", "delay", "timeout"],
      steps: ["Latenzbudget definieren", "Grenzen testen"],
      risks: ["Zu langsame Rückmeldung"],
      mitigations: ["Vorverarbeitung und Caching"],
      roiDrivers: ["Bessere Nutzung"],
      bestPractices: ["Zeitkritische Flows messen"],
      notes: ["Wichtig für Echtzeit-Interaktionen."],
    },
  ),
]

const bestPractices: GenericSeed[] = [
  genericSeed(
    "best-practice-read-only-first",
    "best_practice",
    "Read-only zuerst",
    "Mit lesendem Zugriff starten und Schreibpfade erst später erlauben.",
    ["safety", "integration"],
    ["customer-inbound-support", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Risiko minimieren und eine sichere Basis schaffen.",
      applicability: ["Billing", "Support", "Case work"],
      questions: ["Kann der Use Case schon lesend Nutzen liefern?"],
      criteria: ["Read-only ist möglich"],
      signals: ["read only"],
      steps: ["Lesen", "Verstehen", "erst dann schreiben"],
      risks: ["Zu frühes Schreiben"],
      mitigations: ["Schreibgrenze hart halten"],
      roiDrivers: ["Weniger Fehler"],
      bestPractices: ["Lesen vor Schreiben"],
      notes: ["Passt zu fast jedem ersten KI-Schritt."],
    },
  ),
  genericSeed(
    "best-practice-approval-visible",
    "best_practice",
    "Freigaben sichtbar machen",
    "Menschen sollen erkennen, wo die KI anhalten und Freigabe holen muss.",
    ["approval", "governance"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Kontrollpunkte nicht verstecken.",
      applicability: ["Unlock", "Refund", "Rebooking", "Retention"],
      questions: ["Wo entscheidet ein Mensch?"],
      criteria: ["Freigabepunkt ist dokumentiert"],
      signals: ["approve", "hold"],
      steps: ["Grenze markieren", "Freigabe einbauen"],
      risks: ["Autonomie ohne Kontrolle"],
      mitigations: ["Klares Approval UI"],
      roiDrivers: ["Schnellere, aber sichere Ausführung"],
      bestPractices: ["Freigabe explizit machen"],
      notes: ["Hilft auch bei Audit und Vertrauen."],
    },
  ),
  genericSeed(
    "best-practice-structured-output",
    "best_practice",
    "Strukturiertes Ergebnis",
    "Ausgaben als klare, überprüfbare Felder statt als freier Fließtext zurückgeben.",
    ["structure", "output"],
    ["case-management-and-triage", "customer-inbound-support"],
    ["assessment", "solution_matching"],
    {
      objective: "Nachverfolgbarkeit und Weiterverarbeitung sichern.",
      applicability: ["Tickets", "Dossiers", "Answers"],
      questions: ["Welche Felder braucht das Folge-System?"],
      criteria: ["Output ist maschinenlesbar"],
      signals: ["fields", "json", "status"],
      steps: ["Schema definieren", "Ausgabe validieren"],
      risks: ["Freitext lässt sich schwer weiterverarbeiten"],
      mitigations: ["Validierung und klare Felder"],
      roiDrivers: ["Weniger Nacharbeit"],
      bestPractices: ["Maschinenlesbar liefern"],
      notes: ["Wichtige Grundregel für Assistenzsysteme."],
    },
  ),
  genericSeed(
    "best-practice-escalation",
    "best_practice",
    "Klare Eskalation",
    "Ein definierter Handoff-Pfad verhindert, dass schwierige Fälle stecken bleiben.",
    ["escalation", "handoff"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["assessment", "roadmap"],
    {
      objective: "Sonderfälle sicher an Menschen übergeben.",
      applicability: ["Unklarer Fall", "Sonderfall", "Compliance"],
      questions: ["Wer übernimmt den Ausnahmefall?"],
      criteria: ["Eskalation ist dokumentiert"],
      signals: ["handoff", "manual"],
      steps: ["Grenze erkennen", "Mensch informieren"],
      risks: ["Kein Zuständiger"],
      mitigations: ["Benannter Support-Pfad"],
      roiDrivers: ["Weniger offene Fälle"],
      bestPractices: ["Handoff definieren"],
      notes: ["Ein Muss für schwierige Ausnahmen."],
    },
  ),
  genericSeed(
    "best-practice-measure-baseline",
    "best_practice",
    "Baseline messen",
    "Vor der Lösung den heutigen Zustand und den Zielzustand festhalten.",
    ["roi", "measurement"],
    ["transaction-and-dispute-resolution", "proactive-recovery-and-retention"],
    ["discovery", "assessment"],
    {
      objective: "Wert und Erfolg messbar machen.",
      applicability: ["Alle Use Cases"],
      questions: ["Was ist heute der Ausgangswert?"],
      criteria: ["Baseline und Ziel sind vorhanden"],
      signals: ["baseline", "target", "metric"],
      steps: ["Ist-Zustand dokumentieren", "Zielwert festlegen"],
      risks: ["Vage Erfolgskriterien"],
      mitigations: ["Konkrete Kennzahlen"],
      roiDrivers: ["Messbarer Nutzen"],
      bestPractices: ["Messen vor dem Start"],
      notes: ["Passt direkt zur Discovery-Baseline."],
    },
  ),
  genericSeed(
    "best-practice-audit",
    "best_practice",
    "Jede wichtige Aktion auditieren",
    "Wesentliche Entscheidungen und schreibende Änderungen brauchen einen nachvollziehbaren Verlauf.",
    ["audit", "traceability"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["assessment", "solution_matching", "roadmap"],
    {
      objective: "Nachvollziehbarkeit sichern.",
      applicability: ["Write actions", "approvals", "escalations"],
      questions: ["Was muss später rekonstruierbar sein?"],
      criteria: ["Aktion ist protokolliert"],
      signals: ["audit trail"],
      steps: ["Aktion durchführen", "Log schreiben"],
      risks: ["Unklare Historie"],
      mitigations: ["Audit als Pflicht"],
      roiDrivers: ["Weniger Streitfälle"],
      bestPractices: ["Audit standardisieren"],
      notes: ["Unterstützt Governance und Review."],
    },
  ),
]

const followUpTemplates: GenericSeed[] = [
  genericSeed(
    "follow-up-missing-volume",
    "follow_up_template",
    "Volumen und Häufigkeit",
    "Fragen, die klären, wie oft ein Problem auftritt und wie es heute verteilt ist.",
    ["follow-up", "volume"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["report"],
    {
      objective: "Fehlendes Volumen oder Häufigkeitsschätzung einholen.",
      applicability: ["Wiederkehrende Anfragen"],
      questions: ["Wie oft tritt der Fall pro Woche oder Monat auf?"],
      criteria: ["Volumen ist greifbar"],
      signals: ["frequency", "volume"],
      steps: ["Frequenz nachfragen", "Tages-/Monatsbild festhalten"],
      risks: ["Gefühl statt Zahl"],
      mitigations: ["Beispielzeiträume nennen"],
      roiDrivers: ["Wiederholungsrate"],
      bestPractices: ["Häufigkeit konkretisieren"],
      notes: ["Gut für Support und Triage."],
    },
  ),
  genericSeed(
    "follow-up-missing-baseline",
    "follow_up_template",
    "Baseline und Messmethode",
    "Fragen, die aus einer vagen Aussage eine belastbare Kennzahl machen.",
    ["follow-up", "measurement"],
    ["transaction-and-dispute-resolution", "proactive-recovery-and-retention"],
    ["report"],
    {
      objective: "Basiswert und Messmethode erfragen.",
      applicability: ["Business impact", "KPI", "Target metric"],
      questions: ["Wie wird das heute gemessen?", "Woher stammt der Wert?"],
      criteria: ["Messmethode ist bekannt"],
      signals: ["baseline", "source"],
      steps: ["Messmethode klären", "Quelle dokumentieren"],
      risks: ["Unscharfe Zahlen"],
      mitigations: ["Quelle und Methode festhalten"],
      roiDrivers: ["Verlässliche Zahlen"],
      bestPractices: ["Nie ohne Quelle speichern"],
      notes: ["Passt zur Phase-2-Baseline."],
    },
  ),
  genericSeed(
    "follow-up-approval",
    "follow_up_template",
    "Freigabe und Eskalation",
    "Fragen, die klären, wer wann entscheiden darf und welche Ausnahmefälle existieren.",
    ["follow-up", "approval"],
    ["account-and-access-actions", "transaction-and-dispute-resolution"],
    ["report"],
    {
      objective: "Freigabekette präzisieren.",
      applicability: ["Unlock", "Refund", "Rebooking"],
      questions: ["Wer gibt frei?", "Welche Kriterien gelten?"],
      criteria: ["Freigabe ist eindeutig"],
      signals: ["approve", "reject"],
      steps: ["Freigabestelle erfragen", "Grenze dokumentieren"],
      risks: ["Autonomie ohne Kontrolle"],
      mitigations: ["Approval-Frage explizit stellen"],
      roiDrivers: ["Weniger Rückläufer"],
      bestPractices: ["Freigabekette sichtbar machen"],
      notes: ["Besonders wichtig bei riskanten Aktionen."],
    },
  ),
  genericSeed(
    "follow-up-data-access",
    "follow_up_template",
    "Datenzugriff und Systeme",
    "Fragen, die klären, welche Systeme gelesen oder geschrieben werden dürfen.",
    ["follow-up", "integration"],
    ["customer-inbound-support", "case-management-and-triage"],
    ["report"],
    {
      objective: "Integrations- und Zugriffsgrenzen klären.",
      applicability: ["API", "Backend", "Legacy"],
      questions: ["Welches System ist die führende Quelle?"],
      criteria: ["Zugriffsweg ist bekannt"],
      signals: ["api", "backend", "system"],
      steps: ["Systeme benennen", "Zugriff klären"],
      risks: ["Unklare Integrationsgrenzen"],
      mitigations: ["System of record dokumentieren"],
      roiDrivers: ["Weniger Medienbrüche"],
      bestPractices: ["Systemzugriff vorab klären"],
      notes: ["Wichtig für jede Lösung mit Integration."],
    },
  ),
]

const useCases: UseCaseSeed[] = [
  {
    code: "failed-customer-onboarding",
    title: "Fehlgeschlagenes Customer Onboarding",
    summary:
      "Ein automatisiertes Onboarding scheitert an Mailadresse, API- oder Lizenzkonflikt und benötigt menschliche Korrektur.",
    processCode: "customer-inbound-support",
    taxonomyCodes: ["email-support", "customer-service"],
    patterns: ["verified-exception-resolution", "structured-intake"],
    implementationPatterns: ["read-first-then-act", "human-approval-gate"],
    roiModels: ["aht-reduction", "error-rework-reduction"],
    riskModels: ["identity-risk", "integration-risk"],
    questions: [
      "Welche Fehlermeldungen treten am häufigsten auf?",
      "Wer muss die Korrektur freigeben?",
    ],
    criteria: ["Fehlerursache ist strukturiert erfassbar"],
    bestPractices: ["Freigabe sichtbar machen", "Read-first verwenden"],
    followUps: ["Wie oft tritt der Konflikt auf?"],
    signals: ["onboarding", "error", "approval"],
    steps: ["Fehler erkennen", "Mensch informieren", "Korrektur fortsetzen"],
    risks: ["Lizenz- oder Berechtigungsfehler"],
    mitigations: ["Freigabeprozess und Audit"],
    roiDrivers: ["Weniger manuelle Nacharbeit", "schnelleres Onboarding"],
  },
  {
    code: "in-transit-address-change",
    title: "Dynamische Adressänderung für ein bereits unterwegs befindliches Paket",
    summary:
      "Ein Empfänger möchte ein Paket umleiten, das sich bereits in der Auslieferung befindet, und der Status muss in Echtzeit geprüft werden.",
    processCode: "account-and-access-actions",
    taxonomyCodes: ["booking-reservations", "customer-service"],
    patterns: ["transaction-safe-action", "verified-exception-resolution"],
    implementationPatterns: ["read-first-then-act", "human-approval-gate"],
    roiModels: ["aht-reduction", "recovery-cost-avoidance"],
    riskModels: ["transaction-risk", "identity-risk"],
    questions: [
      "Welche Identitätsprüfung ist vor der Umleitung nötig?",
      "Ist die Umleitung im aktuellen Transportzustand noch erlaubt?",
    ],
    criteria: ["Berechtigung und Umleitbarkeit sind prüfbar"],
    bestPractices: ["Nur auf freigegebene Zustände schreiben"],
    followUps: ["Welche Systeme zeigen den Live-Status?"],
    signals: ["reroute", "status", "confirmation"],
    steps: ["Status prüfen", "Berechtigung prüfen", "Änderung durchführen"],
    risks: ["Falsche Umleitung"],
    mitigations: ["Echtzeit-Abfrage und Freigabe"],
    roiDrivers: ["Weniger operative Eskalation", "schnellere Kundenreaktion"],
  },
  {
    code: "high-volume-status-requests",
    title: "Hochvolumige Bewerber-Statusanfragen",
    summary:
      "Viele identische Statusfragen sollen automatisch beantwortet werden, damit der Support entlastet wird.",
    processCode: "case-management-and-triage",
    taxonomyCodes: ["ticket-management", "crm"],
    patterns: ["status-and-triage-assistance", "structured-intake"],
    implementationPatterns: ["structured-intake", "fallback-and-escalation"],
    roiModels: ["deflection-model", "aht-reduction"],
    riskModels: ["trust-risk", "latency-risk"],
    questions: [
      "Welche Statusstufen werden am häufigsten abgefragt?",
      "Welche Dokumente fehlen typischerweise?",
    ],
    criteria: ["Statusdaten sind zuverlässig abrufbar"],
    bestPractices: ["Strukturierten Output liefern"],
    followUps: ["Welche Statusanfrage führt am häufigsten zu Rückfragen?"],
    signals: ["status", "volume", "deflection"],
    steps: ["Status abfragen", "Antwort strukturieren", "fehlende Dokumente anfordern"],
    risks: ["Falsche oder veraltete Auskunft"],
    mitigations: ["Echtzeit-Lookup und klare Fallbacks"],
    roiDrivers: ["Weniger Supportlast", "schnellere Auskunft"],
  },
  {
    code: "intelligent-ticket-triage",
    title: "Intelligente Ticket-Triage",
    summary:
      "Unstrukturierte Supportfälle werden analysiert, fehlende Informationen erfragt und an den richtigen Zweig weitergereicht.",
    processCode: "case-management-and-triage",
    taxonomyCodes: ["ticket-management", "help-desk"],
    patterns: ["status-and-triage-assistance", "incident-dossier"],
    implementationPatterns: ["structured-intake", "audit-every-change"],
    roiModels: ["aht-reduction", "deflection-model"],
    riskModels: ["trust-risk", "integration-risk"],
    questions: [
      "Welche Eingaben fehlen am häufigsten?",
      "Wie wird heute priorisiert?",
    ],
    criteria: ["Triage-Regeln sind erklärbar"],
    bestPractices: ["Priorisierung transparent halten"],
    followUps: ["Welche fehlenden Daten blockieren die Lösung am stärksten?"],
    signals: ["triage", "priority", "missing data"],
    steps: ["Problem klassifizieren", "Lücken schließen", "Route bestimmen"],
    risks: ["Falsche Priorisierung"],
    mitigations: ["Klare Kategorien und Eskalation"],
    roiDrivers: ["Weniger manuelle Sortierung"],
  },
  {
    code: "end-to-end-returns",
    title: "End-to-End Retourenabwicklung",
    summary:
      "Eine Rückgabe wird verifiziert, ein Label erstellt und der Refund-Prozess angestoßen.",
    processCode: "transaction-and-dispute-resolution",
    taxonomyCodes: ["booking-reservations", "customer-service"],
    patterns: ["verified-exception-resolution", "transaction-safe-action"],
    implementationPatterns: ["read-first-then-act", "audit-every-change"],
    roiModels: ["recovery-cost-avoidance", "error-rework-reduction"],
    riskModels: ["transaction-risk", "compliance-risk"],
    questions: [
      "Welche Rückgabebedingungen gelten?",
      "Wann darf die Erstattung ausgelöst werden?",
    ],
    criteria: ["Rückgabe und Refund sind geklärt"],
    bestPractices: ["Vor Auszahlung prüfen"],
    followUps: ["Welche Bedingungen sind systemseitig prüfbar?"],
    signals: ["return", "refund", "label"],
    steps: ["Retourenberechtigung prüfen", "Label erzeugen", "Refund vorbereiten"],
    risks: ["Unberechtigte Erstattung"],
    mitigations: ["Freigabe und Audit"],
    roiDrivers: ["Weniger manuelle Rückfragen", "schnellere Bearbeitung"],
  },
  {
    code: "billing-explanations",
    title: "Rechnungs-Auskünfte und Kostenerklärung",
    summary:
      "Eine Rechnung wird lesend ausgewertet, Kostentreiber werden erklärt und bei Bedarf wird ein Mensch zur Kulanzfreigabe eingeschaltet.",
    processCode: "transaction-and-dispute-resolution",
    taxonomyCodes: ["customer-service", "crm"],
    patterns: ["read-only-explanation", "verified-exception-resolution"],
    implementationPatterns: ["read-first-then-act", "human-approval-gate"],
    roiModels: ["aht-reduction", "error-rework-reduction"],
    riskModels: ["compliance-risk", "trust-risk"],
    questions: [
      "Welche Kostentreiber sind typisch?",
      "Welche Informationen dürfen nur lesend genutzt werden?",
    ],
    criteria: ["Rechnung ist aus lesenden Quellen erklärbar"],
    bestPractices: ["Read-only starten", "Abweichungen transparent erklären"],
    followUps: ["Welche Datenquellen sind für die Erklärung relevant?"],
    signals: ["billing", "read only", "cost driver"],
    steps: ["Rechnung lesen", "Treiber erklären", "Freigabe pfaden"],
    risks: ["Falsche Kulanz oder falsche Erklärung"],
    mitigations: ["Lesend analysieren, Freigabe separat"],
    roiDrivers: ["Weniger Hotline-Kontakte"],
  },
  {
    code: "invoice-correction",
    title: "Rechnungsreklamation und Korrektur",
    summary:
      "Eine falsch abgerechnete Leistung wird mit CRM- und ERP-Daten abgeglichen, korrigiert und zur Freigabe vorbereitet.",
    processCode: "transaction-and-dispute-resolution",
    taxonomyCodes: ["crm", "customer-service"],
    patterns: ["verified-exception-resolution", "transaction-safe-action"],
    implementationPatterns: ["read-first-then-act", "audit-every-change"],
    roiModels: ["error-rework-reduction", "recovery-cost-avoidance"],
    riskModels: ["transaction-risk", "compliance-risk"],
    questions: [
      "Welche Vertrags- oder Rabattdaten sind relevant?",
      "Wer muss die Korrektur prüfen?",
    ],
    criteria: ["Abgleich und Freigabe sind möglich"],
    bestPractices: ["Korrektur entwerfen, dann prüfen"],
    followUps: ["Welche Felder im CRM und ERP müssen verglichen werden?"],
    signals: ["invoice", "discount", "correction"],
    steps: ["Abgleich", "Korrekturentwurf", "Freigabe"],
    risks: ["Falsche Rechnungskorrektur"],
    mitigations: ["Prüfpfad und Audit"],
    roiDrivers: ["Weniger manuelle Korrekturen"],
  },
  {
    code: "proactive-rebooking",
    title: "Proaktive Umbuchung bei Ausfall",
    summary:
      "Bei Betriebsstörungen werden Kunden proaktiv informiert, Alternativen geprüft und Umbuchungen vorbereitet.",
    processCode: "proactive-recovery-and-retention",
    taxonomyCodes: ["booking-reservations", "guest-communication"],
    patterns: ["proactive-recovery", "transaction-safe-action"],
    implementationPatterns: ["proactive-workflow", "human-approval-gate"],
    roiModels: ["recovery-cost-avoidance", "retention-uplift"],
    riskModels: ["transaction-risk", "latency-risk"],
    questions: [
      "Welche Alternativen sind verfügbar?",
      "Welche Reaktionszeit ist akzeptabel?",
    ],
    criteria: ["Alternative und Reaktionsfenster sind vorhanden"],
    bestPractices: ["Proaktiv statt reaktiv arbeiten"],
    followUps: ["Welche Alternativen kann das System live prüfen?"],
    signals: ["rebooking", "outage", "alternative"],
    steps: ["Störung erkennen", "Alternativen prüfen", "Kunden informieren"],
    risks: ["Zu langsame oder falsche Reaktion"],
    mitigations: ["Latenzbudget und Freigabe"],
    roiDrivers: ["Weniger manuelle Eskalation", "bessere Kundenerfahrung"],
  },
  {
    code: "router-reset-and-dispatch",
    title: "Entstörung und Router-Reset",
    summary:
      "Ein Leitungs- oder Routerproblem wird diagnostiziert, ein Remote-Reset wird ausgelöst oder ein Vor-Ort-Termin koordiniert.",
    processCode: "proactive-recovery-and-retention",
    taxonomyCodes: ["help-desk", "call-centers"],
    patterns: ["verified-exception-resolution", "proactive-recovery"],
    implementationPatterns: ["structured-intake", "fallback-and-escalation"],
    roiModels: ["aht-reduction", "recovery-cost-avoidance"],
    riskModels: ["identity-risk", "integration-risk"],
    questions: [
      "Welche Diagnose ist automatisierbar?",
      "Wann ist ein Vor-Ort-Termin nötig?",
    ],
    criteria: ["Diagnose-API und Eskalation vorhanden"],
    bestPractices: ["Erst Diagnose, dann Aktion"],
    followUps: ["Welche Leitungstests können automatisiert werden?"],
    signals: ["diagnosis", "reset", "dispatch"],
    steps: ["Diagnose durchführen", "Reset oder Termin auslösen"],
    risks: ["Fehlerhafter Fernzugriff"],
    mitigations: ["Legitimation und Grenzwerte"],
    roiDrivers: ["Weniger Hotline-Zeit"],
  },
  {
    code: "cancellation-and-retention",
    title: "Abonnement-Kündigung und Retention",
    summary:
      "Kündigungsgründe werden klassifiziert, ein Retention-Angebot vorbereitet und bei Annahme oder Ablehnung der passende Pfad aktiviert.",
    processCode: "proactive-recovery-and-retention",
    taxonomyCodes: ["sales-support", "crm"],
    patterns: ["proactive-recovery", "read-only-explanation"],
    implementationPatterns: ["proactive-workflow", "human-approval-gate"],
    roiModels: ["retention-uplift", "aht-reduction"],
    riskModels: ["trust-risk", "compliance-risk"],
    questions: [
      "Warum kündigt der Kunde?",
      "Welche Retention-Grenzen gelten?",
    ],
    criteria: ["Retention-Logik ist freigabefähig"],
    bestPractices: ["Angebote nicht autonom überziehen"],
    followUps: ["Welche Gründe werden heute am häufigsten genannt?"],
    signals: ["cancel", "save offer", "retention"],
    steps: ["Grund erfassen", "Angebot prüfen", "Pfad ausführen"],
    risks: ["Zu aggressives Retention-Angebot"],
    mitigations: ["Freigabe und Budgetgrenze"],
    roiDrivers: ["Save rate", "Umsatzsicherung"],
  },
  {
    code: "fnol-dossier",
    title: "Initiale Schadensmeldung (FNOL)",
    summary:
      "Eine Schadensmeldung wird strukturiert aufgenommen, ergänzt und als dossier an die Fachprüfung übergeben.",
    processCode: "case-management-and-triage",
    taxonomyCodes: ["customer-service", "ticket-management"],
    patterns: ["incident-dossier", "structured-intake"],
    implementationPatterns: ["structured-intake", "audit-every-change"],
    roiModels: ["error-rework-reduction", "aht-reduction"],
    riskModels: ["compliance-risk", "trust-risk"],
    questions: [
      "Welche Pflichtdaten sind nötig?",
      "Welche Anhänge müssen eingeholt werden?",
    ],
    criteria: ["Dossier ist fachlich prüfbar"],
    bestPractices: ["Pflichtdaten vor Übergabe absichern"],
    followUps: ["Welche Bilder oder Dokumente fehlen typischerweise?"],
    signals: ["claim", "photos", "dossier"],
    steps: ["Schaden aufnehmen", "Dossier vervollständigen", "prüfen lassen"],
    risks: ["Unvollständiges Dossier"],
    mitigations: ["Pflichtfelder und Nachforderung"],
    roiDrivers: ["Weniger Nacharbeit"],
  },
  {
    code: "fraud-alert-and-card-unlock",
    title: "Fraud-Alert und Kartenentsperrung",
    summary:
      "Ein Betrugsverdacht wird verifiziert, die Legitimität geprüft und die Karte nach Freigabe wieder entsperrt.",
    processCode: "account-and-access-actions",
    taxonomyCodes: ["customer-service", "crm"],
    patterns: ["verified-exception-resolution", "transaction-safe-action"],
    implementationPatterns: ["human-approval-gate", "audit-every-change"],
    roiModels: ["aht-reduction", "recovery-cost-avoidance"],
    riskModels: ["identity-risk", "compliance-risk"],
    questions: [
      "Wie wird die Legitimität geprüft?",
      "Welche Handlung darf erst nach Freigabe passieren?",
    ],
    criteria: ["Legitimation und Freigabe sind getrennt"],
    bestPractices: ["Freigabe und Audit pflegen"],
    followUps: ["Welche MFA-Signale stehen zur Verfügung?"],
    signals: ["fraud", "unlock", "mfa"],
    steps: ["Legitimation", "Prüfung", "Entsperrung"],
    risks: ["Falsche Entsperrung"],
    mitigations: ["MFA und menschliche Freigabe"],
    roiDrivers: ["Schnellere Klärung", "weniger Supportkontakte"],
  },
]

const businessDomain: GenericSeed = {
  code: domainCode,
  kind: "business_domain",
  title: "Customer Operations",
  summary:
    "Der erste und initial implementierte Business-Domain-Scope für die Consulting Knowledge Base.",
  tags: ["customer-operations", "domain"],
  relatedCodes: [
    "customer-inbound-support",
    "case-management-and-triage",
    "account-and-access-actions",
    "transaction-and-dispute-resolution",
    "proactive-recovery-and-retention",
  ],
  stageScopes: ["discovery", "assessment", "prioritization", "solution_matching", "roadmap"],
  details: detailsOf({
    objective: "Customer Operations als wiederverwendbare Domäne strukturieren.",
    applicability: [
      "Email Support",
      "Customer Service",
      "Call Centers",
      "Live Chat",
      "Help Desk",
      "CRM",
      "Ticket Management",
      "Booking & Reservations",
      "Guest Communication",
      "Sales Support",
    ],
    questions: ["Welche Customer-Operations-Prozesse sind im Scope?"],
    criteria: ["Die Domäne ist klar benannt und abgrenzbar."],
    signals: ["support", "service", "operations"],
    steps: ["Domäne benennen", "Scope ordnen", "Wiederverwendbarkeit sicherstellen"],
    risks: ["Zu breite Domäne"],
    mitigations: ["Initial nur Customer Operations"],
    roiDrivers: ["Wiederverwendbare Beratung", "konsistente Taxonomie"],
    bestPractices: ["Domäne als eigenständigen Scope modellieren"],
    notes: ["Die Use Cases des Dokuments wurden darauf normalisiert."],
  }),
}

export const consultingKnowledgeSeed: ConsultingKnowledgeEntry[] = [
  toEntry(businessDomain),
  ...processes.map((process) =>
    toEntry({
      code: process.code,
      kind: "business_process",
      title: process.title,
      summary: process.summary,
      tags: process.tags,
      matchTerms: process.matchTerms,
      taxonomyCodes: process.taxonomyCodes,
      relatedCodes: [],
      stageScopes: ["discovery", "assessment", "prioritization", "solution_matching", "roadmap"],
      details: detailsOf({
        objective: process.summary,
        applicability: process.taxonomyCodes,
        questions: ["Welche Teilprozesse gehören hierher?"],
        criteria: ["Der Prozess ist wiederholbar."],
        signals: process.tags,
        steps: ["Prozess identifizieren", "Schritte strukturieren"],
        risks: ["Zu allgemeine Prozessdefinition"],
        mitigations: ["Mit Taxonomie verknüpfen"],
        roiDrivers: ["Wiederholung", "Standardisierung"],
        bestPractices: ["Prozess und Taxonomie zusammen kuratieren"],
        notes: ["Der Prozess dient als oberster operative Bezugspunkt."],
      }),
    }),
  ),
  ...taxonomyNodes.map((taxonomy) =>
    toEntry({
      code: taxonomy.code,
      kind: "customer_operations_taxonomy",
      title: taxonomy.title,
      summary: taxonomy.summary,
      tags: [taxonomy.processCode],
      matchTerms: taxonomy.matchTerms,
      processCodes: [taxonomy.processCode],
      relatedCodes: [],
      stageScopes: ["discovery", "assessment"],
      details: detailsOf({
        objective: taxonomy.summary,
        applicability: [taxonomy.title],
        questions: ["Wie zeigt sich dieser Teilbereich im Alltag?"],
        criteria: ["Der Teilbereich ist benennbar."],
        signals: [taxonomy.title],
        steps: ["Teilbereich identifizieren"],
        risks: ["Zu grobe Zuordnung"],
        mitigations: ["Mit Prozess verknüpfen"],
        roiDrivers: ["Klarere Einordnung"],
        bestPractices: ["Taxonomie scharf halten"],
        notes: ["Taxonomieeinträge ordnen den Customer-Operations-Scope."],
      }),
    }),
  ),
  // The readiness criteria and the framework evaluate the whole domain, so they
  // are curated against every one of its processes rather than against one.
  ...aiReadinessCriteria.map((criterion) =>
    toEntry({ ...criterion, processCodes: allProcessCodes }),
  ),
  toEntry({ ...assessmentFramework, processCodes: allProcessCodes }),
  ...discoveryQuestions.map(toEntry),
  ...solutionPatterns.map(toEntry),
  ...implementationPatterns.map(toEntry),
  ...roiModels.map(toEntry),
  ...riskModels.map(toEntry),
  ...bestPractices.map(toEntry),
  ...followUpTemplates.map(toEntry),
  ...useCases.flatMap((useCase) => [
    toEntry({
      code: `${useCase.code}-problem`,
      kind: "business_problem",
      title: useCase.title,
      summary: useCase.summary,
      tags: [useCase.processCode, ...useCase.taxonomyCodes],
      matchTerms: useCase.signals,
      processCodes: [useCase.processCode],
      taxonomyCodes: useCase.taxonomyCodes,
      relatedCodes: useCase.patterns,
      stageScopes: ["discovery", "assessment", "prioritization"],
      details: detailsOf({
        objective: useCase.summary,
        applicability: useCase.taxonomyCodes,
        questions: useCase.questions,
        criteria: useCase.criteria,
        signals: useCase.signals,
        steps: useCase.steps,
        risks: useCase.risks,
        mitigations: useCase.mitigations,
        roiDrivers: useCase.roiDrivers,
        bestPractices: useCase.bestPractices,
        notes: useCase.followUps,
      }),
    }),
    toEntry({
      code: useCase.code,
      kind: "ai_use_case",
      title: useCase.title,
      summary: useCase.summary,
      tags: [useCase.processCode, ...useCase.taxonomyCodes],
      matchTerms: useCase.signals,
      problemCodes: [`${useCase.code}-problem`],
      processCodes: [useCase.processCode],
      taxonomyCodes: useCase.taxonomyCodes,
      // The untyped slot: the patterns, ROI and risk models a use case is
      // curated against have no typed slot of their own.
      relatedCodes: [
        ...useCase.patterns,
        ...useCase.implementationPatterns,
        ...useCase.roiModels,
        ...useCase.riskModels,
      ],
      stageScopes: ["assessment", "prioritization", "solution_matching", "roadmap"],
      details: detailsOf({
        objective: useCase.summary,
        applicability: useCase.taxonomyCodes,
        questions: useCase.questions,
        criteria: useCase.criteria,
        signals: useCase.signals,
        steps: useCase.steps,
        risks: useCase.risks,
        mitigations: useCase.mitigations,
        roiDrivers: useCase.roiDrivers,
        bestPractices: useCase.bestPractices,
        notes: useCase.followUps,
      }),
    }),
  ]),
]

function detailsOf(details: ConsultingKnowledgeEntry["details"]): ConsultingKnowledgeEntry["details"] {
  return details
}

function unique<T>(values: T[]): T[] {
  return [...new Set(values)]
}

function toEntry(entry: GenericSeed): ConsultingKnowledgeEntry {
  return {
    code: entry.code,
    kind: entry.kind,
    domainCode,
    title: entry.title,
    summary: entry.summary,
    tags: entry.tags,
    matchTerms: entry.matchTerms ?? [],
    stageScopes: entry.stageScopes,
    taxonomyCodes: entry.taxonomyCodes ?? [],
    processCodes: entry.processCodes ?? [],
    problemCodes: entry.problemCodes ?? [],
    useCaseCodes: entry.useCaseCodes ?? [],
    relatedCodes: entry.relatedCodes,
    details: entry.details,
    sortOrder: sortOrderOf(entry.kind),
    active: true,
    revision: 0,
  }
}

function questionSeed(
  code: string,
  title: string,
  summary: string,
  stageScopes: ConsultingKnowledgeEntry["stageScopes"],
  processCodes: string[],
  frameworkCodes: string[],
  questions: string[],
): GenericSeed {
  return {
    code,
    kind: "discovery_question",
    title,
    summary,
    tags: frameworkCodes,
    processCodes,
    relatedCodes: frameworkCodes,
    stageScopes: unique([...stageScopes, "assessment"]),
    details: detailsOf({
      objective: summary,
      applicability: processCodes,
      questions,
      criteria: ["Die Frage hilft, eine konkrete Lücke zu schließen."],
      signals: processCodes,
      steps: ["Frage stellen", "Antwort in Discovery überführen"],
      risks: ["Zu allgemeine Frage"],
      mitigations: ["Konkreten Bezug nennen"],
      roiDrivers: ["Bessere Discovery-Qualität"],
      bestPractices: ["Fragen an den Use Case binden"],
      notes: ["Diese Vorlage wird im Discovery-Schritt genutzt."],
    }),
  }
}

function genericSeed(
  code: string,
  kind: GenericSeed["kind"],
  title: string,
  summary: string,
  tags: string[],
  processCodes: string[],
  stageScopes: ConsultingKnowledgeEntry["stageScopes"],
  details: ConsultingKnowledgeEntry["details"],
): GenericSeed {
  return {
    code,
    kind,
    title,
    summary,
    tags,
    processCodes,
    relatedCodes: [],
    stageScopes,
    details,
  }
}

function sortOrderOf(kind: ConsultingKnowledgeEntry["kind"]): number {
  const order: Record<ConsultingKnowledgeEntry["kind"], number> = {
    business_domain: 1,
    business_process: 2,
    customer_operations_taxonomy: 3,
    business_problem: 4,
    ai_use_case: 5,
    discovery_question: 6,
    assessment_framework: 7,
    ai_readiness_criterion: 8,
    solution_pattern: 9,
    implementation_pattern: 10,
    roi_model: 11,
    risk_model: 12,
    best_practice: 13,
    follow_up_template: 14,
  }

  return order[kind]
}
